
import scrapy

from avtonet.items import AvtoNetItem

class AvtoNetSpider(scrapy.Spider):
    name = "avtonet"
    allowed_domains = ["avto.net"]
    start_urls = [
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=7500&subcenaMAX=10000',
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=10000&subcenaMAX=12500',
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=12500&subcenaMAX=15000',
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=15000&subcenaMAX=20000',
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=20000&subcenaMAX=25000',
        #'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=&znamka2=&model2=&tip2=&znamka3=&model3=&tip3=&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=0&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=0&kmMax=9999999&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=0&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=25000&subcenaMAX=30000',
        'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=katerikoli%20tip&znamka2=&model2=&tip2=katerikoli%20tip&znamka3=&model3=&tip3=katerikoli%20tip&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=1&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=75000&kmMax=100000&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=25000&subcenaMAX=30000',
        'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=katerikoli%20tip&znamka2=&model2=&tip2=katerikoli%20tip&znamka3=&model3=&tip3=katerikoli%20tip&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=1&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=75000&kmMax=100000&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=20000&subcenaMAX=25000',
        'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=katerikoli%20tip&znamka2=&model2=&tip2=katerikoli%20tip&znamka3=&model3=&tip3=katerikoli%20tip&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=1&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=75000&kmMax=100000&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=15000&subcenaMAX=20000',
        'http://www.avto.net/Ads/results.asp?znamka=&model=&modelID=&tip=katerikoli%20tip&znamka2=&model2=&tip2=katerikoli%20tip&znamka3=&model3=&tip3=katerikoli%20tip&cenaMin=0&cenaMax=999999&cenaNetto=0&cenaDDV=0&brezcene=1&letnikMin=0&letnikMax=2090&bencin=0&zavore=&pogon=0&klima=&servo=&lastnik=&servis=&automatic=0&starost2=999&star1=1&star2=1&star3=&star4=1&star5=&karambolirano=0&oblika=0&ccmMin=0&ccmMax=99999&mocMin=&mocMax=&kmMin=75000&kmMax=100000&kwMin=0&kwMax=999&motortakt=0&motorvalji=0&lokacija=0&izpis=1&sirina=0&dolzina=&dolzinaMIN=0&dolzinaMAX=100&nosilnostMIN=0&nosilnostMAX=999999&lezisc=&presek=0&premer=0&col=0&vijakov=0&vozilo=&plin=&prodajalec=2&estekla=&leder=0&navi=&alufelge=&sibedah=&gretje=&tempomat=&zaklepanje=&vlecna=0&aklima=&SLOavto=&xenonke=&espsistem=&garage=0&airbag=&najem=0&hibrid=&garancija=0&oldtimer=0&barva=&showguarantee=&weltauto=&levjapriloznost=0&G2=&toygar=&citroenselect=0&sedezev=&petzvezdic=0&paketgarancije=&topp=0&EKO=0&door=0&MEN=0&VIN=&broker=0&prikazkategorije=0&kategorija=0&oglasrubrika=1&zaloga=10&presort=2&tipsort=DESC&stran=1&subcenaMIN=12500&subcenaMAX=15000',
    ]

    def parse(self, response):
        for item in response.xpath('//*[@id="compare"]/div'):
            try:
                cleaned_item = item.extract().replace('\t', '').replace('\r\n', '')
                car_brand = cleaned_item.split('<span>')[1].split('</span>')[0].split(' ')[0]
                car_model = cleaned_item.split('<span>')[1].split('</span>')[0].split(' ')[1]
                car_price = cleaned_item.split('<!-- REDNA OBJAVA CENE -->')[1].split(
                    '<!-- KOMENTAR CENE -->'
                )[0].strip().split(' ')[0].replace('.','')
                car_year = cleaned_item.split('<li>Letnik 1.registracije:')[1].split('</li>')[0]
                car_km = cleaned_item.split(' km</li>')[0].split('<li>')[-1]

                # If no miles
                if '<' in car_km:
                    car_km = 'N/A'

                if car_model == 'serija':
                    car_model = cleaned_item.split('<span>')[1].split('</span>')[0].split(' ')[2].replace(':', '')

                avtonet_item = AvtoNetItem()
                avtonet_item['brand'] = car_brand
                avtonet_item['model'] = car_model
                avtonet_item['year'] = car_year
                avtonet_item['price'] = car_price
                avtonet_item['kilometers'] = car_km
                yield avtonet_item

            except:
                continue


        try:
            next_page = response.urljoin(
                response.text.split('<!-- NEXT -->')[1].split('">')[0].replace('<a href="', '').strip()
            )
            if next_page:
                yield scrapy.Request(next_page, self.parse)
        except:
            pass
